### ISSUE TITLE
Division by zero error on some codes.

### ISSUE THREAD

**Issue by jkrysakowski** [khanamiryan/php-qrcode-detector-decoder#141]
I'm getting an error, when trying to decode this code:

![test-fail](https://user-images.githubusercontent.com/3762758/204516702-a413dcb3-0966-452e-8df2-99b2d5a76bad.svg)

and it works fine for this one:

![test-success](https://user-images.githubusercontent.com/3762758/204516744-a038e397-8108-4ad4-90ce-932ce02a4e7b.svg)

The error in the first case is:

```
PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in /home/jakub/Pulpit/qr_test/vendor/khanamiryan/qrcode-detector-decoder/lib/Common/PerspectiveTransform.php:118
Stack trace:
#0 /home/jakub/Pulpit/qr_test/vendor/khanamiryan/qrcode-detector-decoder/lib/Common/PerspectiveTransform.php(52): Zxing\Common\PerspectiveTransform::squareToQuadrilateral()
#1 /home/jakub/Pulpit/qr_test/vendor/khanamiryan/qrcode-detector-decoder/lib/Qrcode/Detector/Detector.php(403): Zxing\Common\PerspectiveTransform::quadrilateralToQuadrilateral()
#2 /home/jakub/Pulpit/qr_test/vendor/khanamiryan/qrcode-detector-decoder/lib/Qrcode/Detector/Detector.php(114): Zxing\Qrcode\Detector\Detector::createTransform()
#3 /home/jakub/Pulpit/qr_test/vendor/khanamiryan/qrcode-detector-decoder/lib/Qrcode/Detector/Detector.php(65): Zxing\Qrcode\Detector\Detector->processFinderPatternInfo()
#4 /home/jakub/Pulpit/qr_test/vendor/khanamiryan/qrcode-detector-decoder/lib/Qrcode/QRCodeReader.php(61): Zxing\Qrcode\Detector\Detector->detect()
#5 /home/jakub/Pulpit/qr_test/vendor/khanamiryan/qrcode-detector-decoder/lib/QrReader.php(91): Zxing\Qrcode\QRCodeReader->decode()
#6 /home/jakub/Pulpit/qr_test/test.php(8): Zxing\QrReader->decode()
#7 {main}
  thrown in /home/jakub/Pulpit/qr_test/vendor/khanamiryan/qrcode-detector-decoder/lib/Common/PerspectiveTransform.php on line 118

```

**Comment by edson-nascimento** [comment]
Same problem here
