### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by powtac** [khanamiryan/php-qrcode-detector-decoder#15]
**This file can not be decoded with QrReader!** it just returns `(bool)false`. But the text encoded in the QR Code is `w_537244_40`. 

```
$QrReader = new QrReader('wrong.png');
echo $QrReader->text();
```

![wrong](https://cloud.githubusercontent.com/assets/36167/13143483/8bdc0a22-d644-11e5-9c8f-34ff3adcbff5.png)

The correct result can be proved with the [online Zxing.org encoder here](https://zxing.org/w/decode?u=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F36167%2F13143483%2F8bdc0a22-d644-11e5-9c8f-34ff3adcbff5.png). It returns: 

```
Raw text              w_537244_40
Raw bytes             40 27 75 f1 01 a1 93 d1   00 d7 cd 0c 00 ec 11 ec
Barcode format        QR_CODE
Parsed Result Type	  TEXT
Parsed Result	      w_537244_40

```

**Comment by powtac** [comment]
Another image that can not be decoded. Should contains `w_537241_108` but returns `(bool)false`. :-(

![wrong2](https://cloud.githubusercontent.com/assets/36167/13148315/1c2205c4-d65d-11e5-937e-f280093a6a44.png)

**Comment by jlemale** [comment]
Unfortunately you're right. How did you generate those qr codes ? (I'm not a developer on this project but just curious)

**Comment by powtac** [comment]
Those images where created by an PHP library. TCPDF

**Comment by jlemale** [comment]
Just read http://www.tcpdf.org/doc/code/classTCPDF2DBarcode.html
Which type did you use ? 
QRCODE : QRcode Low error correction
QRCODE,L : QRcode Low error correction
QRCODE,M : QRcode Medium error correction
QRCODE,Q : QRcode Better error correction
QRCODE,H : QR-CODE Best error correction

If you use a different one, is QrReader working ?

**Comment by powtac** [comment]
Default settings

**Comment by powtac** [comment]
It is not the creation lib that fails. The generated codes can be read via common smartphone readers!

**Comment by jlemale** [comment]
Yeah I just wanted to check if the error correction could have been an issue for this reader. But I guess no..

**Comment by powtac** [comment]
What I discovered as well: when running the creation of the QR codes a different code for the same content is created. It seems like there are around 3 different versions of QR codes for the same text. I did a quick search and found a random part in the QR lib, so this is ok. BUT only one of the three QR codes fail with the detector!

**Comment by powtac** [comment]
Similar to #12 and #13

**Comment by jamiedunns** [comment]
i have a similar issue with the attached, i have created many QR codes with the same structure but different event id, but for some reason {"Event ID":"219619"} as the content just doesnt work, any ideas?

it was created using phpqrcode
QRcode::png({"Event ID":"219619"},false,QR_ECLEVEL_L,35);

![219619 5](https://cloud.githubusercontent.com/assets/17644582/13637029/0307f1ac-e5fd-11e5-995e-2d6ebf08ac88.png)

**Comment by qhxin** [comment]
i have the same issue, so ,how did u solve it?😂

**Comment by powtac** [comment]
I have not solved it.

**Comment by qhxin** [comment]
@powtac i tried to resize the qrcode to different sizing tmp image, such as 300px,400px,500px, 600px. so it works better and all of my test image is passed.

![](http://ww1.sinaimg.cn/large/a13e4f59gw1fb4bn48jz5j20k70gtte6.jpg)

**Comment by jlemale** [comment]
I don't know about you guys but I had to recognise Qr Codes that I generated. So after a qrcode generation I checked if I could read it with this library before printing it otherwise I would create a new one.
But I guess most of you don't create the qr codes.. 
GL..

**Comment by powtac** [comment]
Actually I made the same kind of workaround.

**Comment by qhxin** [comment]
i don't create the qr codes, actually it's a part of my spider , so, i have to try to stretch it to different sizes to identify, that's too bad, but there's no other way.😂

**Comment by githubjeka** [comment]
To fix my issue like as your issue, I used `imagecopyresampled` 
For example you can see my code:

```php
$width = imagesx($tempResource);
$height = imagesy($tempResource);

for ($zoom = 100; $zoom >= 10; $zoom -= 10) {
    $new_width = $width * $zoom / 100;
    $new_height = $height * $zoom / 100;
    $zoomResource = imagecreate(800, 350);

    imagecopyresampled(
        $zoomResource,
        $imageResource,
        0,
        0,
        0,
        0,
        $new_width,
        $new_height,
        $width,
        $height
    );

    imagepng($zoomResource, $pathTempPng, 0, PNG_NO_FILTER);
    imagedestroy($zoomResource);

    try {
        $qrcode = new QrReader($pathTempPng);
        $numText = $qrcode->text();
        if ($numText) {
            echo ' FIND ' . $numText . ', ';
            break;
        }
    } catch (\InvalidArgumentException $e) {
        $numText = null;
    }

    echo '{' . $zoom . ' | ' . $numText . ' }, ';
}
```

The percentage of detected QRcodes increased from 10% to 90% for me.

**Comment by ball00n-** [comment]
I had the very same issue happen with me too. I used the hack @githubjeka provided but it ended up giving me 90% success rate too. So I just played around with numbers and found out that usage of zoom step = 5 will increase the success rate even further. I'm planning to add a fallback to https://github.com/dsiddharth2/php-zxing library too. It's a bit slower and also gives me about 90% success rate but on different images. I think I might add another fallback and just try and post my image to https://zxing.org unless it's against website's TOS (would be happy if anyone could enlighten me on the subject).

**Comment by powtac** [comment]
**Both images contain the string `w_7585681_2319`!**

Version 1.0.2 version crashing for this image:
CRASH:
 ![content_not_detectable_by_QrReader](https://user-images.githubusercontent.com/36167/58085824-bfe4f780-7bbd-11e9-8c68-ea68635f7429.png)

But works for this image: 
OK:
![content_detectable_by_QrReader](https://user-images.githubusercontent.com/36167/58085823-bfe4f780-7bbd-11e9-9e19-e7b5ee5e2931.png)

**Both images contain the string `w_7585681_2319`!**

This is the error message:
```
Fatal error:  Uncaught InvalidArgumentException in /usr/vendors/php-qrcode-detector-decoder/Qrcode/Decoder/Version.php:121
Stack trace:
#0 /usr/vendors/php-qrcode-detector-decoder/Qrcode/Decoder/Version.php(112): Zxing\Qrcode\Decoder\Version::getVersionForNumber(0)
#1 /usr/vendors/php-qrcode-detector-decoder/Qrcode/Detector/Detector.php(84): Zxing\Qrcode\Decoder\Version::getProvisionalVersionForDimension(17)
#2 /usr/vendors/php-qrcode-detector-decoder/Qrcode/Detector/Detector.php(69): Zxing\Qrcode\Detector\Detector->processFinderPatternInfo(Object(Zxing\Qrcode\Detector\FinderPatternInfo))
#3 /usr/vendors/php-qrcode-detector-decoder/Qrcode/QRCodeReader.php(62): Zxing\Qrcode\Detector\Detector->detect(NULL)
#4 /usr/vendors/php-qrcode-detector-decoder/QrReader.php(80): Zxing\Qrcode\QRCodeReader->decode(Object(Zxing\BinaryBitmap))
#5 /www/htdocs in /usr/vendors/php-qrcode-detector-decoder/Qrcode/Decoder/Version.php on line 121
```

https://zxing.org/w/decode is able to decode both(!) images with the exact same result:

![grafik](https://user-images.githubusercontent.com/36167/58086091-44d01100-7bbe-11e9-8620-7b40acac73ad.png)

**Comment by powtac** [comment]
This pull request seems to be related: https://github.com/khanamiryan/php-qrcode-detector-decoder/pull/62 it suppresses the InvalidArgumentException exception. But still is not able to read the code.

**Comment by Tinywan** [comment]
To fix my issue like as your issue, I used `composer require topthink/think-image`
For example you can see my code:
```
...
$file_path = $dir_path . '/upload.png';
$image = Image::open($file_path);
$qrReaderPath = $dir_path . '/qrReader.png';
$image->thumb(150, 150)->save($qrReaderPath);
$qrcode = new QrReader($qrReaderPath);
if (!$qrcode->text()) {
    return ['status' => -1, 'msg' => 'decode error'];
}
return ['status' => 1, 'msg' => 'decode success', 'url' => $qrcode->text()];
```

**Comment by shoaib-sme** [comment]
@githubjeka can you please tell me in which file you added this custom code? is it part of QrReader.php? or you created a custom file, from where you call this code?

Thank you.

**Comment by githubjeka** [comment]
@shoaib-sme in my code. After the tried
```php
$qrcode = new QrReader($pathImage);
$numText = $qrcode->text();

if ($numText == null) {
 // this
}
```

**Comment by shoaib-sme** [comment]
@githubjeka  thank you sir for your quick reply. Cheers :)

**Comment by EaintHmueThapye98** [comment]
> To fix my issue like as your issue, I used `composer require topthink/think-image` For example you can see my code:
> 
> ```
> ...
> $file_path = $dir_path . '/upload.png';
> $image = Image::open($file_path);
> $qrReaderPath = $dir_path . '/qrReader.png';
> $image->thumb(150, 150)->save($qrReaderPath);
> $qrcode = new QrReader($qrReaderPath);
> if (!$qrcode->text()) {
>     return 'error';
> }
> return 'success';
> ```

Your solution saved my day! Thanks a bunch <3

**Comment by EaintHmueThapye98** [comment]
> To fix my issue like as your issue, I used `imagecopyresampled` For example you can see my code:
> 
> ```
> $width = imagesx($imageResource);
> $height = imagesy($imageResource);
> 
> for ($zoom = 100; $zoom >= 10; $zoom -= 10) {
>     $new_width = $width * $zoom / 100;
>     $new_height = $height * $zoom / 100;
>     $zoomResource = imagecreate(800, 350);
> 
>     imagecopyresampled(
>         $zoomResource,
>         $imageResource,
>         0,
>         0,
>         0,
>         0,
>         $new_width,
>         $new_height,
>         $width,
>         $height
>     );
> 
>     imagepng($zoomResource, $pathTempPng, 0, PNG_NO_FILTER);
>     imagedestroy($zoomResource);
> 
>     try {
>         $qrcode = new QrReader($pathTempPng);
>         $numText = $qrcode->text();
>         if ($numText) {
>             echo ' FIND ' . $numText . ', ';
>             break;
>         }
>     } catch (\InvalidArgumentException $e) {
>         $numText = null;
>     }
> 
>     echo '{' . $zoom . ' | ' . $numText . ' }, ';
> }
> ```
> 
> The percentage of detected QRcodes increased from 10% to 90% for me.

Your solution saved my day! Thanks a bunch <3
